{% set name = "aioca" %}
{% set version = "1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aioca-{{ version }}.tar.gz
  sha256: 9b07598d59295d9ee701e0c83f151ca8e8da5cd2642390772ee5b988f54db12e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - epicscorelibs >=7.0.3.99.4.0
    - typing-extensions

test:
  imports:
    - aioca
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dls-controls/aioca
  summary: Asynchronous Channel Access client for asyncio and Python using libca via ctypes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
